### ISSUE TITLE
Module parse failed: Unexpected character '' (1:0)

### ISSUE THREAD

**Issue by saadfrhan** [integration-os/integrationos#6] opened 2024-04-17 06:11 UTC
## Error screenshot

![Screenshot from 2024-04-17 11-09-47](https://github.com/integration-os/integrationos/assets/36201799/5d406aa2-f1f4-4b0d-bc3d-22d8e378b975)

## Reproduce error

https://githubbox.com/saadfrhan/integrationos-demo

I wrote envs on a .env.development.local file.

**Comment by moekatib** [comment] 2024-04-18 15:29
Hello @saadfrhan,

Thanks for bringing this up! It looks like Webpack is trying to process a `.node` binary file and isn't set up to handle it right now. You can fix this by adding `node-loader` to your project:

1. Install `node-loader`:
   ```bash
   npm install --save-dev node-loader
   ```

2. Add this to your `next.config.js`:
   ```javascript
   const nextConfig = {
     webpack: (config, { isServer }) => {
       if (!isServer) {
         config.module.rules.push({
           test: /\.node$/,
           loader: 'node-loader',
         });
       }
       return config;
     },
   }

   module.exports = nextConfig
   ```

Restart your server after these changes, and you should be all set. Let me know how it goes!

Cheers!

**Comment by saadfrhan** [comment] 2024-04-18 15:46
I followed the steps and pushed the changes to the repo. It's showing the same behavior.

![image](https://github.com/integration-os/integrationos/assets/36201799/ae570b51-9804-4b97-ab10-736dad6009f1)

**Comment by moekatib** [comment] 2024-04-18 16:40
Can you please give me some info about your OS. It looks like a build issue.

**Comment by saadfrhan** [comment] 2024-04-18 16:45
![image](https://github.com/integration-os/integrationos/assets/36201799/40fa204c-9015-453e-bcb6-1d2aa15fc59d)

**Comment by moekatib** [comment] 2024-04-18 18:32
Turns out, handling node binaries in Next.js needs a bit of special attention.

Our team managed to sort it out with these steps:

1. Run `npm install nextjs-node-loader --force` (force flag is needed due to some eslint incompatibilities, but it's all good, nothing to worry about).
2. Update `next.config.js` with the custom loader setup for `.node` files.

Here's the snippet for our `next.config.js` that did the trick:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { dev, isServer, webpack, nextRuntime }) => {
    config.module.rules.push({
      test: /\.node$/,
      use: [
        {
          loader: "nextjs-node-loader",
        },
      ],
    });

    return config;
  }
};
export default nextConfig;
```

Should work after this. If you bump into any more quirks, let me know!

**Comment by saadfrhan** [comment] 2024-04-19 09:34
Thanks! It worked. 🙌😊

**Comment by saadfrhan** [comment] 2024-04-19 09:49
It worked on the windows but its throwing errors on the terminal:
![image](https://github.com/integration-os/integrationos/assets/36201799/085a36eb-fe5c-4e6d-9b1c-05b7b31bdbd8)

**Comment by moekatib** [comment] 2024-04-19 18:57
Are you by any chance trying to bundle the application for a different OS? Also, does the UI show with the activated integrations?

**Comment by saadfrhan** [comment] 2024-04-19 19:43
I didn't activate any integration. I only clicked the button and it loaded the integrations correctly but threw errors on the terminal.

https://integrationos-demo.vercel.app/
It deployed successfully but throwing errors:
![image](https://github.com/integration-os/integrationos/assets/36201799/35ed4b9c-b850-4b53-bfca-09475ef584a7)

**Comment by saadfrhan** [comment] 2024-04-19 20:05
When I deployed it to Vercel, it threw errors the same as in the screenshot and an error which says that it felt the corsHeaders as a route name. 

![image](https://github.com/integration-os/integrationos/assets/36201799/56a37da5-0c6d-4260-b65e-4e45196431b2)

So when I removed the export from corsHeaders, it deployed it but it threw CORS error on the console.

**Comment by moekatib** [comment] 2024-04-19 20:55
This could be due to the binary requirements when bundling in different OS. Our team will look into this and will get back to you early next week.

Again, thank you very much for sharing this with us and providing these helpful comments.

**Comment by moekatib** [comment] 2024-04-24 19:50
Our team has identified the cause of the issue. It seems the warning from Next.js' build system can be ignored. It appears that Next.js tries to cache every package, even those that are dynamically loaded, likely to speed up builds. 

To fix your code for deployment on Vercel, remove the `export` from `export const corsHeaders` in your `route.ts`.

I am going to close this issue, put feel free to reopen if you still have any issues.

**Closed by moekatib** 2024-04-24 19:50 UTC
Labels: bug

**Comment by saadfrhan** [comment] 2024-04-24 20:25
I removed the export from the corsHeaders.

It ran successfully, but the terminal is showing same errors:
![image](https://github.com/integration-os/integrationos/assets/36201799/7fd7ea49-b27b-4391-9538-547b7068305d)

Vercel deployment is also showing same errors:
![image](https://github.com/integration-os/integrationos/assets/36201799/aaa74d74-cf0b-4695-95c7-f73fdba5623b)

and I am getting cors error on production:
![image](https://github.com/integration-os/integrationos/assets/36201799/9f534f00-e4c5-4438-8531-2922728eab6c)

**Comment by moekatib** [comment] 2024-04-25 00:25
These errors can be fully ignored, they have no impact on the application. As for the CORS, you will need to set the route in 'page.tsx' to the correspondent Vercel server url.

Please let me know if it does not work.
